### PR TITLE
Use binary from `POCKET_IC_BIN` if set

### PR DESCRIPTION
**Pull request by ZenVoich**
Hi. I'm currently adding toolchain version management to mops (moc, wasmtime, pocket-ic)

And I want to use pic-js with custom `POCKET_IC_BIN` to run specified version of pocket-ic.

### CODE REVIEW

**Comment by nathanosdev** [comment]
Thanks for the suggestion @ZenVoich.
What use case do you have to use a different version of pocket IC than the one that's included with the library?

My concern with this is that there can be breaking changes in different versions of the pocket IC binary. If you use a newer version than what's included in the library then you will have errors.

An example of the issues that come from this can be seen in this issue: https://github.com/dfinity/pocketic/issues/2

**Comment by ZenVoich** [comment]
> What use case do you have to use a different version of pocket IC than the one that's included with the library?

I want to add an option for a package/project to specify `pocket-ic` version. So on one machine(and one mops cli) can be used different versions of `pocket-ic`.

> My concern with this is that there can be breaking changes in different versions of the pocket IC binary. If you use a newer version than what's included in the library then you will have errors.

Yes, that can be problem.

I think if pocket-ic server will support REST API (https://github.com/dfinity/pocketic/issues/4) then pic-js won't be needed and I can deploy canisters to pocket-ic via dfx.

**Comment by nathanosdev** [comment]
I'm not sure if I understand exactly what you're aiming to achieve with MOPS, could you give me some more details so I can understand the use case better?

> I think if pocket-ic server will support REST API (https://github.com/dfinity/pocketic/issues/4) then pic-js won't be needed and I can deploy canisters to pocket-ic via dfx.

I cannot say when, but it's safe to say that pocket-ic will support this at some point. If you don't need the additional support that's provided by the pocket-ic clients (such as changing system time or backing up/restoring stable memory) and you simply just need to deploy canisters, then using pocket-ic with DFX is probably the better way to go.

**Comment by ZenVoich** [comment]
> could you give me some more details so I can understand the use case better?

For example, you have multiple Motoko projects, and you want to use different versions of `pocket-ic` in each project

**Comment by nathanosdev** [comment]
I see. This is something that I would like end users of PicJS to not think about. They should only think about PicJS versions and not PocketIC server versions. Similar to how developers using Playwright (or a similar e2e automation frameworks) would think about Playwright versions rather than ChromeDriver versions. Otherwise developers need to manually match the PocketIC server version with the PicJS themselves and this could be error prone.

Since they are only thinking of PicJS versions, then this should be managed by NPM (or PNPM/Yarn), which they will need to write their tests using PicJS anyway. If I'm missing something please let me know, but I don't think this is a good direction to go in. Managing PicJS versions with NPM, and PocketIC server versions with Mops sounds like it will cause issues for developers.

**Pull request closed without merging**
